apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: app-runtime
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: demo-api
          image: nginx:1.29.7-alpine
          ports:
            - containerPort: 80
          env:
            - name: NATS_URL
              value: nats://nats:4222
            - name: POSTGRES_URL
              value: postgres://postgres:postgres@postgres:5432/postgres
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: app-runtime
spec:
  clusterIP: None
  selector:
    app: demo-api
  ports:
    - port: 80
      targetPort: 80
