apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - policy-exception.yaml
  - traefik.yaml
  - nats.yaml
  - postgres.yaml
  - demo-api.yaml
  - demo-worker.yaml
  - smoke-test.yaml
