apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: baseline-networkpolicy
spec:
  validationFailureAction: Enforce
  rules:
    - name: default-deny-for-namespace
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-system
                - kube-public
                - kube-node-lease
                - flux-system
                - kyverno
                - default
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: default-deny
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
            ingress: []
            egress:
              - to:
                  - namespaceSelector: {}
                ports:
                  - protocol: UDP
                    port: 53
